openapi: 3.0.4
info:
  title: Flowgear Demo ZA
  description: 'Site Key: b9b91bfa-d098-47b7-8ea6-5b669a0141f9, Environment Key: 293c8e8a-f9d5-4bf6-80f2-6663f93eceba'
  version: '2025.12.09'
servers:
  - url: https://demodomain2023sa.flowgear.net
paths:
  /webinars/apps/cw-tickets:
    get:
      summary: 'ConnectWise Get tickets [WAW]'
      description: 'ConnectWise Get tickets [WAW] (Revision 260bf5c2cee025db18301771f0b7741dd1c938ad, Published 2025-12-08T17:54:59.0824877+00:00, Workflow Key 3453b9a9-3b1a-4f59-85fb-49b231b5a285).'
      operationId: 3453b9a9-3b1a-4f59-85fb-49b231b5a285
      parameters:
        - name: export
          in: query
          required: true
          schema:
            type: string
          example: 'false'
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                    summary:
                      type: string
                    priority:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                        name:
                          type: string
                    company:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                        name:
                          type: string
                    owner:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                        name:
                          type: string
                    status:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                        name:
                          type: string
                    contactName:
                      type: string
                    contactEmailAddress:
                      type: string
                    _info:
                      type: object
                      properties:
                        dateEntered:
                          type: string
              example:
                - id: 0
                  summary: string
                  priority:
                    id: 0
                    name: string
                  company:
                    id: 0
                    name: string
                  owner:
                    id: 0
                    name: string
                  status:
                    id: 0
                    name: string
                  contactName: string
                  contactEmailAddress: string
                  _info:
                    dateEntered: string
  '/webinars/apps/cw-tickets/{id}':
    patch:
      summary: 'ConnectWise Update ticket priority [WAW]'
      description: 'ConnectWise Update ticket priority [WAW] (Revision 8cb971b1a3fb5ede6262257af2b3af7c28893688, Published 2025-12-08T17:55:53.2144455+00:00, Workflow Key 3d6958d0-9b4d-4ec1-b5b5-13d65efeee34).'
      operationId: 3d6958d0-9b4d-4ec1-b5b5-13d65efeee34
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: '3'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                PriorityId:
                  type: integer
                  format: int32
            example:
              PriorityId: 4
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8: { }
  /webinars/apps/cw-tickets/priorities:
    get:
      summary: 'ConnectWise Ticket Priority Options [WAW]'
      description: 'ConnectWise Ticket Priority Options [WAW] (Revision 01413f4398c79361a6f6b5bebc6c4906ce0e2797, Published 2025-12-08T17:34:23.8225513+00:00, Workflow Key 7d608cef-f856-4dab-82fc-a6ef5071e414).'
      operationId: 7d608cef-f856-4dab-82fc-a6ef5071e414
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                    name:
                      type: string
                    color:
                      type: string
                    sortOrder:
                      type: integer
                      format: int32
                    defaultFlag:
                      type: boolean
                    imageLink:
                      type: string
                    urgencySortOrder:
                      type: string
                    _info:
                      type: object
                      properties:
                        lastUpdated:
                          type: string
                        updatedBy:
                          type: string
                        image_href:
                          type: string
              example:
                - id: 1
                  name: Priority 2 - Quick Response
                  color: Orange
                  sortOrder: 4
                  defaultFlag: false
                  imageLink: ../../common/images/infoIcons/urgencyColors/orange.gif
                  urgencySortOrder: ../../common/images/infoIcons/urgencyColors/orange.gif
                  _info:
                    lastUpdated: '10/20/2004 8:31:35 PM'
                    updatedBy: zadmin
                    image_href: https://automation.connectwisedev.com/v4_6_release/apis/3.0//service/priorities/1/image?lastModified=2004-10-20T20:31:35Z
  /webinars/apps/sage-failed-invoices:
    get:
      summary: 'Sage Intacct Get Failed Invoices [WAW]'
      description: 'Sage Intacct Get Failed Invoices [WAW] (Revision 9767bb118520ac502903f23b87b9dd886035bece, Published 2025-12-08T16:32:36.0403887+00:00, Workflow Key 13cb20ae-9546-42b9-86db-84d71cd54591).'
      operationId: 13cb20ae-9546-42b9-86db-84d71cd54591
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                    invoiceNumber:
                      type: string
                    customerId:
                      type: string
                    customerName:
                      type: string
                    invoiceDate:
                      type: string
                    dueDate:
                      type: string
                    txnAmount:
                      type: integer
                      format: int32
                    txnCurrency:
                      type: string
                    glAccountId:
                      type: string
                    departmentId:
                      type: string
                    locationId:
                      type: string
                    description:
                      type: string
                    errorMessage:
                      type: string
                    errorSeverity:
                      type: string
                    status:
                      type: string
                    retryCount:
                      type: integer
                      format: int32
                    failedAt:
                      type: string
              example:
                - id: 1
                  invoiceNumber: INV-2024-0001
                  customerId: CUST_INVALID
                  customerName: Acme Corporation
                  invoiceDate: '2024-12-01'
                  dueDate: '2024-12-31'
                  txnAmount: 15420
                  txnCurrency: USD
                  glAccountId: 4000-00
                  departmentId: SALES
                  locationId: HQ
                  description: Consulting Services - November
                  errorMessage: Customer ID 'CUST_INVALID' not found in Sage Intacct
                  errorSeverity: critical
                  status: failed
                  retryCount: 0
                  failedAt: '12/2/2024 8:15:00 AM'
    put:
      summary: 'Sage Intacct Update Failed Invoice [WAW]'
      description: 'Sage Intacct Update Failed Invoice [WAW] (Revision 6e9e8906c640e9f02caa2a41ee08797025566466, Published 2025-12-08T17:38:32.1000910+00:00, Workflow Key a2a50558-d193-4c22-bcd1-d9600e191e16).'
      operationId: a2a50558-d193-4c22-bcd1-d9600e191e16
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                invoiceNumber:
                  type: string
                customerId:
                  type: string
                customerName:
                  type: string
                invoiceDate:
                  type: string
                dueDate:
                  type: string
                txnAmount:
                  type: integer
                  format: int32
                txnCurrency:
                  type: string
                glAccountId:
                  type: string
                departmentId:
                  type: string
                locationId:
                  type: string
                description:
                  type: string
                errorMessage:
                  type: string
                errorSeverity:
                  type: string
                status:
                  type: string
                retryCount:
                  type: integer
                  format: int32
                failedAt:
                  type: string
            example:
              id: 1
              invoiceNumber: INV-2024-0001
              customerId: CUST_INVALID
              customerName: Acme Corporation
              invoiceDate: '2024-12-01'
              dueDate: '2024-12-31'
              txnAmount: 15420
              txnCurrency: USD
              glAccountId: 4000-00
              departmentId: SALES
              locationId: HQ
              description: Consulting Services - November
              errorMessage: Customer ID 'CUST_INVALID' not found in Sage Intacct
              errorSeverity: critical
              status: failed
              retryCount: 0
              failedAt: '12/3/2024 8:15:00 AM'
      responses:
        '200':
          description: Response Example
          content:
            application/json: { }
  '/webinars/apps/sage-failed-invoices/{invoiceNumber}/retry':
    post:
      summary: 'Sage Intacct Set Invoice to Retry [WAW]'
      description: 'Sage Intacct Set Invoice to Retry [WAW] (Revision 4b3cf38e7c44dd41758a3d607ad6206448e031c7, Published 2025-12-08T17:57:48.3474891+00:00, Workflow Key d2d6739d-9a49-4199-a313-7b8a61e28d6c).'
      operationId: d2d6739d-9a49-4199-a313-7b8a61e28d6c
      parameters:
        - name: invoiceNumber
          in: path
          required: true
          schema:
            type: string
          example: INV-2024-0001
      responses:
        '200':
          description: Response Example
          content:
            application/json: { }
  /webinars/apps/salesforce-leads:
    patch:
      summary: 'Salesforce Update Lead Status [WAW]'
      description: 'Salesforce Update Lead Status [WAW] (Revision 1e95dc62f363806a4835b8193c8974428d357111, Published 2025-12-08T17:58:37.5973231+00:00, Workflow Key 165c6b66-35cc-4aea-b638-ac740749fac8).'
      operationId: 165c6b66-35cc-4aea-b638-ac740749fac8
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Id:
                  type: string
                Status:
                  type: string
            example:
              Id: id
              Status: Working - Contacted
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: object
                properties:
                  Response:
                    type: object
                    properties:
                      success:
                        type: string
                      errors:
                        type: object
                        properties:
                          statusCode:
                            type: string
                          message:
                            type: string
                          fields:
                            type: string
                      request:
                        type: object
                        properties:
                          attributes:
                            type: object
                            properties:
                              type:
                                type: string
                              referenceId:
                                type: string
                          Id:
                            type: string
                          Status:
                            type: string
              example:
                Response:
                  success: 'false'
                  errors:
                    statusCode: MALFORMED_ID
                    message: 'Lead ID: id value of incorrect type: id'
                    fields: Id
                  request:
                    attributes:
                      type: Lead
                      referenceId: item0
                    Id: id
                    Status: Working - Contacted
    get:
      summary: 'Salesforce Get Leads [WAW]'
      description: 'Salesforce Get Leads [WAW] (Revision 759d21d32cc4496bd934ca4733042e7708b87f2d, Published 2025-12-08T14:42:00.9662581+00:00, Workflow Key feb14d5b-32d6-4316-80a3-91f62c9f9ce3).'
      operationId: feb14d5b-32d6-4316-80a3-91f62c9f9ce3
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        Id:
                          type: string
                        Name:
                          type: string
                        FirstName:
                          type: string
                        LastName:
                          type: string
                        Company:
                          type: string
                        Email:
                          type: string
                        Phone:
                          type: string
                        Status:
                          type: string
                        Rating:
                          type: string
                        CreatedDate:
                          type: string
              example:
                data:
                  - Id: 00Q0Y000003QL1iUAG
                    Name: Phyllis Cotton
                    FirstName: Phyllis
                    LastName: Cotton
                    Company: Abbott Insurance
                    Email: pcotton@abbottins.net
                    Phone: (703) 757-1000
                    Status: Open - Not Contacted
                    Rating: 
                    CreatedDate: '2/24/2017 8:12:55 AM'
  /webinars/apps/salesforce-status-leads:
    get:
      summary: 'Salesforce Status Options [WAW]'
      description: 'Salesforce Status Options [WAW] (Revision 7e1cdcc4def8014ccbd7d94c11b9b376a3b06bcf, Published 2025-12-08T18:00:07.6475094+00:00, Workflow Key 1dd1d779-102c-4d4c-930b-9356a9ca3abc).'
      operationId: 1dd1d779-102c-4d4c-930b-9356a9ca3abc
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        label:
                          type: string
              example:
                items:
                  - key: Open - Not Contacted
                    label: Open - Not Contacted
  /webinars/apps/sql-contacts:
    get:
      summary: 'SQL Get Contacts [WAW]'
      description: 'SQL Get Contacts [WAW] (Revision 9d6926aef9b6aafe1b7581465126f3c9becc20de, Published 2025-12-08T14:00:30.4352685+00:00, Workflow Key 13a974d8-25a0-4ae0-8b89-004329fa6119).'
      operationId: 13a974d8-25a0-4ae0-8b89-004329fa6119
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: object
                properties:
                  Result:
                    type: object
                    properties:
                      Table:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            first_name:
                              type: string
                            last_name:
                              type: string
                            company_name:
                              type: string
                            address:
                              type: string
                            city:
                              type: string
                            county:
                              type: string
                            state:
                              type: string
                            zip:
                              type: string
                            phone1:
                              type: string
                            phone:
                              type: string
                            email:
                              type: string
              example:
                Result:
                  Table:
                    - id: '1'
                      first_name: James
                      last_name: Tiger Nixon
                      company_name: 'Benton, John B Jr'
                      address: 6649 N Blue Gum St
                      city: New Orleans
                      county: Orleans
                      state: LA
                      zip: '70116'
                      phone1: 504-621-8927
                      phone: 504-845-1427
                      email: jbutt@gmail.com
    post:
      summary: 'SQL Update Contact [WAW]'
      description: 'SQL Update Contact [WAW] (Revision a8902261bd6c4e83fd267739ed59465acae28aac, Published 2025-12-08T14:01:24.6995563+00:00, Workflow Key 2a65ad01-3123-43e8-98b4-88e0b65b169c).'
      operationId: 2a65ad01-3123-43e8-98b4-88e0b65b169c
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                company_name:
                  type: string
                address:
                  type: string
                city:
                  type: string
                county:
                  type: string
                state:
                  type: string
                zip:
                  type: string
                phone1:
                  type: string
                phone:
                  type: string
                email:
                  type: string
            example:
              id: '1'
              first_name: James
              last_name: Tiger Nixon
              company_name: 'Benton, John B Jr'
              address: 6649 N Blue Gum St
              city: New Orleans
              county: Orleans
              state: LA
              zip: '70116'
              phone1: 504-621-8927
              phone: 504-845-1427
              email: jbutt@gmail.com
      responses:
        '200':
          description: Response Example
          content:
            application/json: { }
  /webinars/apps/status-chart:
    get:
      summary: 'Simple Chart - Status data [WAW]'
      description: 'Simple Chart - Status data [WAW] (Revision 8a899ddc01046c6ee4e4f5b7a9b6f74d323b61fc, Published 2025-12-08T18:01:09.0934032+00:00, Workflow Key e80daaa3-1095-470a-b079-c36425e026b3).'
      operationId: e80daaa3-1095-470a-b079-c36425e026b3
      responses:
        '200':
          description: Response Example
          headers:
            Content-Type:
              description: 'Example: application/json; charset=utf8'
              schema:
                type: string
              example: application/json; charset=utf8
            Access-Control-Allow-Origin:
              description: 'Example: *'
              schema:
                type: string
              example: '*'
          content:
            application/json; charset=utf8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category:
                      type: string
                    count:
                      type: integer
                      format: int32
              example:
                - category: Completed
                  count: 145
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: 'Bearer {ApiKey}'
      name: Authorization
      in: header
security:
  - ApiKeyAuth: [ ]